# Workshop Web Scraping (Semana 5 - Pandas)

# Pandas DataFrames
DataFrames no Pandas são uma estrutura de dados bidimensional (2-D) definida no pandas que consiste em linhas e colunas.

In [3]:
import pandas as pd

**Criando um DataFrame**

Criação de data frame com os valores das series da oficina passada.

In [4]:
numeric_data = [1, 7, 2] # dado numérico

index = ["x", "y", "z"] # índices pré-definido

data = pd.Series(numeric_data, index)

df = pd.DataFrame(data)

print(df)

   0
x  1
y  7
z  2

Aqui, data pode ser:


1.   Um ou mais dicionários
2.   uma ou mais Series
3.   2D-numpy Ndarray (Array multidimensional)

Lembrando que index por padrão começa por 0: 0, 1, 2 ..., (n-1)

**Criar um DataFrame do Pandas a partir de vários dicionários**

Criando um Dataframe com dois dicionários.

In [5]:
# Definição dicionario 1
dict1 = {'a': 1, 'b': 2, 'c': 3, 'd': 4}

# Definição dicionario 2
dict2 = {'a': 5, 'b': 6, 'c': 7, 'd': 8, 'e': 9}

# Definição de Data com dict1 e dict2
Data = {'primeiro': dict1, 'segundo': dict2}

# Create DataFrame
df = pd.DataFrame(Data)

print(df)

   primeiro  segundo
a       1.0        5
b       2.0        6
c       3.0        7
d       4.0        8
e       NaN        9

**Converter lista de dicionários em um DataFrame do Pandas**

Aqui, pegamos três dicionários e com a ajuda da função from_dict() os convertemos em Pandas DataFrame.

In [8]:
data_c = [
  {'A': 5, 'B': 0, 'C': 3, 'D': 3},
  {'A': 7, 'B': 9, 'C': 3, 'D': 5},
  {'A': 2, 'B': 4, 'C': 7, 'D': 6, 'E': 32}
 ]

df = pd.DataFrame.from_dict(data_c)

print(df)

   A  B  C  D     E
0  5  0  3  3   NaN
1  7  9  3  5   NaN
2  2  4  7  6  32.0

**Criar DataFrame de várias séries**

Criando um dataframe de três séries.

In [9]:
# Definição da series 1
s1 = pd.Series([1, 3, 4, 5, 6, 2, 9])

# Definição da series 2
s2 = pd.Series([1.1, 3.5, 4.7, 5.8, 2.9, 9.3])

# Definição da series 3
s3 = pd.Series(['a', 'b', 'c', 'd', 'e'])

# Definição de Data
Data = {'primeiro':s1, 'segundo':s2, 'terceiro':s3}

# Criar DataFrame
df = pd.DataFrame(Data)

print(df)

   primeiro  segundo terceiro
0         1      1.1        a
1         3      3.5        b
2         4      4.7        c
3         5      5.8        d
4         6      2.9        e
5         2      9.3      NaN
6         9      NaN      NaN

**Converter um array em Pandas Dataframe**

Ao criar um DataFrame de arrays 2D, as dimensões do array 2D devem ser as mesmas.

In [10]:
# Definição de array 2d 1
d1 =[[2, 3, 4], [5, 6, 7], [2,3,5]]

# Definição de array 2d 2
d2 =[[2, 4, 8], [1, 3, 9], [2.23343,'B',0]]

# Definição de Data
Data ={'primeiro': d1, 'segundo': d2}

# Create DataFrame
df_2d = pd.DataFrame(Data)

df_2d

    primeiro          segundo
0  [2, 3, 4]        [2, 4, 8]
1  [5, 6, 7]        [1, 3, 9]
2  [2, 3, 5]  [2.23343, B, 0]

# Acesso e Manipulação dos dados

Lendo dados de um arquivo do tipo .csv

In [19]:
df = pd.read_csv("https://raw.githubusercontent.com/fmassaretto/Workshop-WebScraping/main/arquivos/employees.csv")

#print(type(df))

#print(df)

#df.head(30)
df.tail(10)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
991,Rose,Female,8/25/2002,5:12 AM,134505.0,11.051,True,Marketing
992,Anthony,Male,10/16/2011,8:35 AM,112769.0,11.625,True,Finance
993,Tina,Female,5/15/1997,3:53 PM,56450.0,19.040,True,Engineering
994,George,Male,6/21/2013,5:47 PM,98874.0,4.479,True,Marketing
995,Henry,NaN,11/23/2014,6:09 AM,132483.0,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392.0,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914.0,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500.0,11.985,False,Business Development
999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1000,Albert,Male,5/15/2012,6:24 PM,129949.0,10.169,True,Sales

**isnull**

Conferindo quais valores sao nulos, retorna true se o valor for nulo e false se tem algum valor na celula

In [15]:
df.isnull()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
996,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False
999,True,True,True,True,True,True,True,True
1000,False,False,False,False,False,False,False,False

**fillna**

Preeenchendo um valor que você definir no lugar dos valores nulos (no caso do pandas, ele substitui nulo (None) por NaN (Not a Number))

In [16]:

# df["Gender"].fillna("sem valor") # substirui um campo nulo (NaN) de uma coluna específica
df.fillna("nao ok", inplace = True) # substirui um campo nulo (NaN) de todo o dataframe
df.tail(50)

<ipython-input-16-97f9617c533f>:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'nao ok' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.fillna("nao ok", inplace = True) # substirui um campo nulo (NaN) de todo o dataframe

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
951,nao ok,Female,9/14/2010,5:19 AM,143638.0,9.662,nao ok,nao ok
952,Teresa,Female,1/22/2013,3:17 PM,113425.0,11.907,True,Human Resources
953,Randy,Male,2/25/2012,5:33 AM,57266.0,14.077,False,Product
954,Joe,Male,1/19/1980,4:06 PM,119667.0,1.148,True,Finance
955,Sarah,Female,8/17/2014,11:08 PM,127118.0,11.176,False,Legal
956,Beverly,Female,10/17/1986,12:51 AM,80838.0,8.115,False,Engineering
957,Jeffrey,Male,2/3/1984,1:26 PM,70990.0,15.901,True,Sales
958,Gloria,Female,10/24/1987,4:43 AM,39833.0,9.631,False,Engineering
959,Albert,Male,9/19/1992,2:35 AM,45094.0,5.85,True,Business Development
960,Stephen,Male,10/29/1989,11:34 PM,93997.0,18.093,True,Business Development
961,Antonio,nao ok,6/18/1989,9:37 PM,103050.0,3.05,False,Legal
962,Jonathan,Male,8/21/2013,12:45 AM,121797.0,16.923,False,Product
963,Ann,Female,9/23/1994,11:15 AM,89443.0,17.94,True,Sales
964,Bruce,Male,5/7/1980,8:00 PM,35802.0,12.391,True,Sales
965,Catherine,Female,9/25/1989,1:31 AM,68164.0,18.393,False,Client Services
966,Louis,Male,8/16/2011,5:19 PM,93022.0,9.146,True,Human Resources
967,Thomas,Male,3/12/2016,3:10 PM,105681.0,19.572,False,Engineering
968,Louise,Female,3/27/1995,10:27 PM,43050.0,11.671,False,Distribution
969,Linda,Female,2/4/2010,8:49 PM,44486.0,17.308,True,Engineering
970,Alice,Female,9/3/1988,8:54 PM,63571.0,15.397,True,Product
971,Patrick,Male,12/30/2002,2:01 AM,75423.0,5.368,True,Business Development
972,Victor,nao ok,7/28/2006,2:49 PM,76381.0,11.159,True,Sales
973,Russell,Male,5/10/2013,11:08 PM,137359.0,11.105,False,Business Development
974,Harry,Male,8/30/2011,6:31 PM,67656.0,16.455,True,Client Services
975,Susan,Female,4/7/1995,10:05 PM,92436.0,12.467,False,Sales
976,Denise,Female,10/19/1992,5:42 AM,137954.0,4.195,True,Legal
977,Sarah,Female,12/4/1995,9:16 AM,124566.0,5.949,False,Product
978,Sean,Male,1/17/1983,2:23 PM,66146.0,11.178,False,Human Resources
979,Ernest,Male,7/20/2013,6:41 AM,142935.0,13.198,True,Product
980,Kimberly,Female,1/26/2013,12:57 AM,46233.0,8.862,True,Engineering
981,James,Male,1/15/1993,5:19 PM,148985.0,19.28,False,Legal
982,Rose,Female,4/6/1982,10:43 AM,91411.0,8.639,True,Human Resources
983,John,Male,12/23/1982,10:35 PM,146907.0,11.738,False,Engineering
984,Maria,Female,10/15/2011,4:53 PM,43455.0,13.04,False,Engineering
985,Stephen,nao ok,7/10/1983,8:10 PM,85668.0,1.909,False,Legal
986,Donna,Female,11/26/1982,7:04 AM,82871.0,17.999,False,Marketing
987,Gloria,Female,12/8/2014,5:08 AM,136709.0,10.331,True,Finance
988,Alice,Female,10/5/2004,9:34 AM,47638.0,11.209,False,Human Resources
989,Justin,nao ok,2/10/1991,4:58 PM,38344.0,3.794,False,Legal
990,Robin,Female,7/24/1987,1:35 PM,100765.0,10.982,True,Client Services
991,Rose,Female,8/25/2002,5:12 AM,134505.0,11.051,True,Marketing
992,Anthony,Male,10/16/2011,8:35 AM,112769.0,11.625,True,Finance
993,Tina,Female,5/15/1997,3:53 PM,56450.0,19.04,True,Engineering
994,George,Male,6/21/2013,5:47 PM,98874.0,4.479,True,Marketing
995,Henry,nao ok,11/23/2014,6:09 AM,132483.0,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392.0,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914.0,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500.0,11.985,False,Business Development
999,nao ok,nao ok,nao ok,nao ok,nao ok,nao ok,nao ok,nao ok
1000,Albert,Male,5/15/2012,6:24 PM,129949.0,10.169,True,Sales

**dropna**

Remove linhas que contenham valor ou valores nulos

In [23]:
df = df.dropna() # remove qualquer linha que tenha pelo menos um valor nulo
df

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308.0,6.945,True,Marketing
2,Maria,Female,4/23/1993,11:17 AM,130590.0,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705.0,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004.0,1.389,True,Client Services
5,Dennis,Male,4/18/1987,1:35 AM,115163.0,10.125,False,Legal
...,...,...,...,...,...,...,...,...
994,George,Male,6/21/2013,5:47 PM,98874.0,4.479,True,Marketing
996,Phillip,Male,1/31/1984,6:30 AM,42392.0,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914.0,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500.0,11.985,False,Business Development
1000,Albert,Male,5/15/2012,6:24 PM,129949.0,10.169,True,Sales

In [24]:
data = df.dropna(how = 'all') # remove a linha em que todos os valores são nulos
data

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308.0,6.945,True,Marketing
2,Maria,Female,4/23/1993,11:17 AM,130590.0,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705.0,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004.0,1.389,True,Client Services
5,Dennis,Male,4/18/1987,1:35 AM,115163.0,10.125,False,Legal
...,...,...,...,...,...,...,...,...
994,George,Male,6/21/2013,5:47 PM,98874.0,4.479,True,Marketing
996,Phillip,Male,1/31/1984,6:30 AM,42392.0,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914.0,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500.0,11.985,False,Business Development
1000,Albert,Male,5/15/2012,6:24 PM,129949.0,10.169,True,Sales

**loc e iloc**

loc e iloc são utilizados para fatiar (separar) um conjunto de dados de um dataframe.

Com loc, conseguimos acessar multiplas colunas e fazer alguma logica que só retorne os dados que queremos analisar.

In [25]:
df.loc[df['Gender'] == 'Male']

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308.0,6.945,True,Marketing
3,Jerry,Male,3/4/2005,1:00 PM,138705.0,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004.0,1.389,True,Client Services
5,Dennis,Male,4/18/1987,1:35 AM,115163.0,10.125,False,Legal
12,Brandon,Male,12/1/1980,1:08 AM,112807.0,17.492,True,Human Resources
...,...,...,...,...,...,...,...,...
994,George,Male,6/21/2013,5:47 PM,98874.0,4.479,True,Marketing
996,Phillip,Male,1/31/1984,6:30 AM,42392.0,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914.0,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500.0,11.985,False,Business Development
1000,Albert,Male,5/15/2012,6:24 PM,129949.0,10.169,True,Sales

In [26]:
df.loc[(df['Gender'] == 'Male') & (df['Salary'] > 100000.0)].head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
3,Jerry,Male,3/4/2005,1:00 PM,138705.0,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004.0,1.389,True,Client Services
5,Dennis,Male,4/18/1987,1:35 AM,115163.0,10.125,False,Legal
12,Brandon,Male,12/1/1980,1:08 AM,112807.0,17.492,True,Human Resources
13,Gary,Male,1/27/2008,11:40 PM,109831.0,5.831,False,Sales

In [27]:
df.loc[0:10, ['First Name','Salary']]

  First Name    Salary
0    Douglas   97308.0
2      Maria  130590.0
3      Jerry  138705.0
4      Larry  101004.0
5     Dennis  115163.0
6       Ruby   65476.0
8     Angela   95570.0
9    Frances  139852.0

iloc é baseado na posição onde quero encontrar o dado, ex.:

In [28]:
df.iloc[0, 4]

97308.0

sendo,

primeiro parametro: linha=0

segundo parametro: coluna=4

Também posso ter uma faixa de dados, ex.:

In [ ]:
df.iloc[0:5, 3:6]

  Last Login Time    Salary  Bonus %
0        12:42 PM   97308.0    6.945
1         6:53 AM   61933.0    4.170
2        11:17 AM  130590.0   11.858
3         1:00 PM  138705.0    9.340
4         4:47 PM  101004.0    1.389

**Query**

Permite fazer consultas no dataframe procurando por um valor específico

In [29]:
df.query('`First Name` == "Maria"')['Salary'] # Atenção: metodo query, quando o nome da coluna tem espaço usamos acento grave (`)
                                              # ao invés de aspas simples ou dupla

# extra: com o metodo describe conseguimos ter uma análise estatística
# df.query('`First Name` == "Maria"')['Salary'].describe()

2      130590.0
198     36067.0
936     96250.0
984     43455.0
Name: Salary, dtype: float64

# Exercício

1.   Ler o arquivo csv: https://raw.githubusercontent.com/fmassaretto/Workshop-WebScraping/main/arquivos/TabelaA%C3%A7%C3%B5es.csv
2.   Remover todos os valores nulos
3. Aplicar a seguinte lógica: retornar os dados que o "Val. Min" seja maior que 20.0, o "Val. Max" menor que 50.0 e "Var. Ano (%)" seja positivo